version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  pre_build:
    commands:
      - npm install jest
      - npm install aws-sdk-client-mock @aws-sdk/client-dynamodb
  build:
    commands:
      - npm test
  post_build:
    commands:
      - zip -r function.zip .
      - echo "Deploying to Lambda"
      - aws lambda update-function-code --function-name kelompok3_yosep --zip-file fileb://function.zip

artifacts:
  files:
    - '**/*'
  discard-paths: yes
